const StudentActionTypes = {
  GET_STUDENT_LIST_START: "GET_STUDENT_LIST_START",
  GET_STUDENT_LIST_SUCCESS: "GET_STUDENT_LIST_SUCCESS",
  GET_STUDENT_LIST_FAILURE: "GET_STUDENT_LIST_FAILURE",
  CLEANUP_STUDENT_STORE: "CLEANUP_STUDENT_STORE",
};

export default StudentActionTypes;
