const StudentActionTypes = {
  // Get the list of students for a course.
  GET_STUDENT_LIST_START: "GET_STUDENT_LIST_START",
  GET_STUDENT_LIST_SUCCESS: "GET_STUDENT_LIST_SUCCESS",
  GET_STUDENT_LIST_FAILURE: "GET_STUDENT_LIST_FAILURE",

  // Get the student attendance data list for the given date for a course.
  GET_STUDENT_ATTENDANCE_LIST_START: "GET_STUDENT_ATTENDANCE_LIST_START",
  GET_STUDENT_ATTENDANCE_LIST_SUCCESS: "GET_STUDENT_ATTENDANCE_LIST_SUCCESS",
  GET_STUDENT_ATTENDANCE_LIST_FAILURE: "GET_STUDENT_ATTENDANCE_LIST_FAILURE",

  // Misc.
  CLEAN_STUDENT_LIST: "CLEAN_STUDENT_LIST",
  CLEANUP_STUDENT_STORE: "CLEANUP_STUDENT_STORE",
};

export default StudentActionTypes;
