const CourseActionTypes = {
  GET_COURSE_LIST_START: "GET_COURSE_LIST_START",
  GET_COURSE_LIST_SUCCESS: "GET_COURSE_LIST_SUCCESS",
  GET_COURSE_LIST_FAILURE: "GET_COURSE_LIST_FAILURE",
  CLEAR_COURSE_LIST: "CLEAR_COURSE_LIST",
  ADD_COURSE_START: "ADD_COURSE_START",
  ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
  ADD_COURSE_FAILURE: "ADD_COURSE_FAILURE",
};

export default CourseActionTypes;
