const AttendanceActionTypes = {
  GET_ATTENDANCE_CIPHERTEXT_START: "GET_ATTENDANCE_CIPHERTEXT_START",
  GET_ATTENDANCE_CIPHERTEXT_SUCCESS: "GET_ATTENDANCE_CIPHERTEXT_SUCCESS",
  GET_ATTENDANCE_CIPHERTEXT_FAILURE: "GET_ATTENDANCE_CIPHERTEXT_FAILURE",
};

export default AttendanceActionTypes;
