const AttendanceActionTypes = {
  // Get Ciphertexts for attendance
  GET_ATTENDANCE_CIPHERTEXT_START: "GET_ATTENDANCE_CIPHERTEXT_START",
  GET_ATTENDANCE_CIPHERTEXT_SUCCESS: "GET_ATTENDANCE_CIPHERTEXT_SUCCESS",
  GET_ATTENDANCE_CIPHERTEXT_FAILURE: "GET_ATTENDANCE_CIPHERTEXT_FAILURE",

  // Get datelists for attendance fetch
  GET_DATELIST_START: "GET_DATELIST_START",
  GET_DATELIST_SUCCESS: "GET_DATELIST_SUCCESS",
  GET_DATELIST_FAILURE: "GET_DATELIST_FAILURE",
};

export default AttendanceActionTypes;
